### ISSUE TITLE
Don't persistently store credentials on any object  of the patch

### ISSUE THREAD

**Issue by ffont** [albincorreya/Freesound_Max-MSP_Modules#1]
`client_id` and `client_secret` parameters should not be persistently stored in the patch so they aren't loaded. This happens in dictionary objects which store their contents. This behaviour can be disabled with the `embed` property.

**Comment by albincorreya** [comment]
Thanks, also added an functionality to logout, login and authorise with different freesound accounts. All the user credentials are deleted once they logout from their user account inside the patch.
